# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{url}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tal Atlas"]
  s.date = %q{2011-01-31}
  s.description = %q{A simple url object to allow for OO based manipulation and usage of a url}
  s.email = %q{me@tal.by}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "lib/url.rb",
    "lib/url/classer.rb",
    "lib/url/handlers.rb",
    "lib/url/handlers/as_json_handler.rb",
    "lib/url/handlers/base_json_handler.rb",
    "lib/url/handlers/net_handler.rb",
    "lib/url/handlers/ty_handler.rb",
    "lib/url/handlers/yajl_handler.rb",
    "lib/url/helper_classes.rb",
    "lib/url/response.rb",
    "spec/classer_spec.rb",
    "spec/handler_spec.rb",
    "spec/json_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/url_spec.rb"
  ]
  s.homepage = %q{http://github.com/talby/url}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A URL object}
  s.test_files = [
    "spec/classer_spec.rb",
    "spec/handler_spec.rb",
    "spec/json_spec.rb",
    "spec/spec_helper.rb",
    "spec/url_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.0"])
  end
end

